#@apiUrl = http://localhost:3030/users
@apiUrl = https://notes-kim.azurewebsites.net/notes


@token = {{${{$dotenv TOKEN}}}}
//@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6ImtpbSIsImlhdCI6MTUxNjIzOTAyMn0.BNUdkm-MKlXQmbaSWsZBYUeQbY3GosMU9FbwOt1YKik

###
GET {{apiUrl}}
Authorization: Bearer {{token}}


###
GET {{apiUrl}}/64f9a89c3192a9bf9d0e740a
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "My own note"
}

### 
PATCH {{apiUrl}}/64f9a89c3192a9bf9d0e740a
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "My updated note"
}

###
DELETE {{apiUrl}}/64f9aa07539b7df1d8de2397
Authorization: Bearer {{token}}

###