@apiUrl = http://localhost:3030/users
#@apiUrl = https://notes-kim.azurewebsites.net/notes
@token = {{$dotenv TOKEN}}

###
GET {{apiUrl}}
Authorization: Bearer {{token}}


###
GET {{apiUrl}}/6500459ad2c4f9f6b7da41cc
Authorization: Bearer {{token}}

### Logga in på /users/login
POST {{apiUrl}}/login
Content-Type: application/json

{
    "email": "kimm@foo.bar",
    "password": "Password123"
}

### skapa ny användare
POST {{apiUrl}}
Content-Type: application/json

{
    "email": "kimmm@foo.bar",
    "password": "Password123"
}

### 
PATCH {{apiUrl}}/6500459ad2c4f9f6b7da41cc
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "password": "Password123"

}

###
DELETE {{apiUrl}}/64f9aa07539b7df1d8de2397
Authorization: Bearer {{token}}

###